// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EF_Day1.Models;

public partial class Player
{
    public int id { get; set; }

    public string Name { get; set; }

    public string Position { get; set; }

    public int? Number { get; set; }

    public string Nationality { get; set; }

    public int? Goals { get; set; }

    public int? Matches { get; set; }

    public int? YellowCards { get; set; }

    public int? RedCards { get; set; }

    public int? Salary { get; set; }
}