// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API_Lab.Models;

public partial class Course
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string CourseName { get; set; }

    [StringLength(50)]
    public string CourseDesc { get; set; }

    public int? Duration { get; set; }
}